@startuml
actor User
participant ":TextUi" as UI
participant ":Main" as Main
participant ":Parser" as Parser
participant ":DeleteCommand" as DeleteCmd
participant ":QuestionBank" as LastShownQB
participant ":QuestionBank" as MainQB
participant ":CommandHistory" as History
participant ":QuestionLogger" as Logger
participant ":CommandResult" as Result

User -> UI : input "delete 1"
UI -> Main : "delete 1"

Main -> Parser : parseCommand("delete 1")
Parser -> DeleteCmd : new DeleteCommand(index, mainBank, lastShownBank, commandHistory)
Parser --> Main : DeleteCommand

Main -> DeleteCmd : execute()

alt invalid index
    DeleteCmd --> Main : throws IllegalCommandException
else valid index
    DeleteCmd -> LastShownQB : getQuestion(index)
    DeleteCmd -> MainQB : findQuestionIndex(question)
    alt not found in main
        DeleteCmd --> Main : throws IllegalCommandException
    else found in main
        DeleteCmd -> MainQB : removeQuestion(index)
        DeleteCmd -> History : add(this)
        DeleteCmd -> Logger : logDeletedQuestion(question)
        DeleteCmd -> Result : new CommandResult("Deleted ...")
        DeleteCmd --> Main : Result
    end
end

Main -> UI : displayResults(Result)
@enduml
